{
  "openapi": "3.0.1",
  "info": {
    "title": "Osuny",
    "version": "v1"
  },
  "servers": [
    {
      "url": "/api/osuny/v1"
    }
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "security": [
    {
      "api_key": []
    }
  ],
  "components": {
    "securitySchemes": {
      "api_key": {
        "type": "apiKey",
        "name": "X-Osuny-Token",
        "in": "header"
      }
    },
    "schemas": {
      "communication_website": {
        "type": "object",
        "title": "Communication::Website",
        "properties": {
          "id": {
            "type": "string"
          },
          "url": {
            "type": "string",
            "nullable": true
          },
          "deuxfleurs": {
            "type": "object",
            "properties": {
              "hosting": {
                "type": "boolean"
              },
              "identifier": {
                "type": "string",
                "nullable": true
              }
            }
          },
          "features": {
            "type": "object",
            "properties": {
              "agenda": {
                "type": "boolean"
              },
              "portfolio": {
                "type": "boolean"
              },
              "posts": {
                "type": "boolean"
              }
            }
          },
          "git": {
            "type": "object",
            "properties": {
              "branch": {
                "type": "string",
                "nullable": true
              },
              "endpoint": {
                "type": "string",
                "nullable": true
              },
              "provider": {
                "type": "string",
                "nullable": true
              },
              "repository": {
                "type": "string",
                "nullable": true
              }
            }
          },
          "showcase": {
            "type": "object",
            "properties": {
              "present": {
                "type": "boolean"
              },
              "highlighted": {
                "type": "boolean"
              },
              "tags": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "name": {
                      "type": "string"
                    },
                    "slug": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "localizations": {
            "type": "object",
            "description": "Localizations of the website. The key is the language's ISO 639-1 code.",
            "additionalProperties": {
              "$ref": "#/components/schemas/communication_website_localization"
            },
            "minProperties": 1
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "communication_website_localization": {
        "type": "object",
        "title": "Communication::Website::Localization",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "published": {
            "type": "boolean"
          },
          "published_at": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "social_email": {
            "type": "string",
            "nullable": true
          },
          "social_facebook": {
            "type": "string",
            "nullable": true
          },
          "social_github": {
            "type": "string",
            "nullable": true
          },
          "social_instagram": {
            "type": "string",
            "nullable": true
          },
          "social_linkedin": {
            "type": "string",
            "nullable": true
          },
          "social_mastodon": {
            "type": "string",
            "nullable": true
          },
          "social_peertube": {
            "type": "string",
            "nullable": true
          },
          "social_tiktok": {
            "type": "string",
            "nullable": true
          },
          "social_vimeo": {
            "type": "string",
            "nullable": true
          },
          "social_x": {
            "type": "string",
            "nullable": true
          },
          "social_youtube": {
            "type": "string",
            "nullable": true
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "communication_website_post": {
        "type": "object",
        "title": "Communication::Website::Post",
        "properties": {
          "id": {
            "type": "string"
          },
          "migration_identifier": {
            "type": "string",
            "nullable": true
          },
          "full_width": {
            "type": "boolean"
          },
          "localizations": {
            "type": "object",
            "description": "Localizations of the post. The key is the language's ISO 639-1 code.",
            "additionalProperties": {
              "$ref": "#/components/schemas/communication_website_post_localization"
            }
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          }
        }
      },
      "communication_website_post_localization": {
        "type": "object",
        "title": "Communication::Website::Post::Localization",
        "properties": {
          "id": {
            "type": "string"
          },
          "migration_identifier": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string"
          },
          "featured_image": {
            "type": "object",
            "properties": {
              "blob_id": {
                "type": "string",
                "nullable": true
              },
              "alt": {
                "type": "string",
                "nullable": true
              },
              "credit": {
                "type": "string",
                "nullable": true
              },
              "url": {
                "type": "string",
                "nullable": true
              }
            }
          },
          "meta_description": {
            "type": "string",
            "nullable": true
          },
          "pinned": {
            "type": "boolean",
            "nullable": true
          },
          "published": {
            "type": "boolean"
          },
          "published_at": {
            "type": "string",
            "format": "date-time",
            "nullable": true
          },
          "slug": {
            "type": "string"
          },
          "subtitle": {
            "type": "string",
            "nullable": true
          },
          "summary": {
            "type": "string",
            "nullable": true
          },
          "text": {
            "type": "string",
            "nullable": true
          },
          "blocks": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/communication_block"
            }
          }
        }
      },
      "communication_block": {
        "type": "object",
        "title": "Communication::Block",
        "properties": {
          "migration_identifier": {
            "type": "string"
          },
          "template_kind": {
            "type": "string",
            "description": "Template kind of the blocks.",
            "enum": [
              "agenda",
              "call_to_action",
              "chapter",
              "contact",
              "datatable",
              "definitions",
              "embed",
              "features",
              "files",
              "gallery",
              "image",
              "key_figures",
              "license",
              "links",
              "locations",
              "organizations",
              "pages",
              "papers",
              "persons",
              "posts",
              "projects",
              "programs",
              "sound",
              "testimonials",
              "timeline",
              "title",
              "video",
              "volumes"
            ]
          },
          "title": {
            "type": "string"
          },
          "position": {
            "type": "integer"
          },
          "published": {
            "type": "boolean",
            "default": true
          },
          "html_class": {
            "type": "string",
            "description": "For advanced use. Add an HTML class for custom purposes."
          },
          "data": {
            "type": "object",
            "description": "Data of the block. The structure depends on the template kind.",
            "additionalProperties": true
          }
        }
      }
    }
  },
  "paths": {
    "/communication/websites/{website_id}/posts": {
      "get": {
        "summary": "Lists a website's posts",
        "tags": [
          "Communication::Website::Post"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "name": "website_id",
            "in": "path",
            "description": "Website identifier",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "examples": {
                  "Successful operation": {
                    "value": [
                      {
                        "id": "03f9a88a-084d-535b-baf7-9008b43969c2",
                        "migration_identifier": "test-post-fixture-1",
                        "full_width": false,
                        "localizations": {
                          "fr": {
                            "id": "16a1d9cf-f9eb-5ded-914d-dd421b5d395b",
                            "migration_identifier": "test-post-fixture-1-fr",
                            "title": "Test",
                            "featured_image": {
                              "blob_id": null,
                              "alt": null,
                              "credit": null,
                              "url": null
                            },
                            "meta_description": null,
                            "pinned": null,
                            "published": true,
                            "published_at": "2010-11-28T01:00:00.000+01:00",
                            "slug": "test",
                            "subtitle": null,
                            "summary": null,
                            "text": null,
                            "created_at": "2024-12-07T14:57:12.969+01:00",
                            "updated_at": "2024-12-07T14:57:12.969+01:00"
                          }
                        },
                        "created_at": "2024-12-07T14:57:12.989+01:00",
                        "updated_at": "2024-12-07T14:57:12.989+01:00"
                      },
                      {
                        "id": "253a800b-42fe-5586-8114-0c8d6913bbbc",
                        "migration_identifier": null,
                        "full_width": false,
                        "localizations": {
                          "fr": {
                            "id": "a979b73e-e42b-54de-97d4-df21605e49c0",
                            "migration_identifier": null,
                            "title": "Test 2",
                            "featured_image": {
                              "blob_id": null,
                              "alt": null,
                              "credit": null,
                              "url": null
                            },
                            "meta_description": null,
                            "pinned": null,
                            "published": true,
                            "published_at": "2010-11-28T01:00:00.000+01:00",
                            "slug": "test-2",
                            "subtitle": null,
                            "summary": null,
                            "text": null,
                            "created_at": "2024-12-07T14:57:12.969+01:00",
                            "updated_at": "2024-12-07T14:57:12.969+01:00"
                          }
                        },
                        "created_at": "2024-12-07T14:57:12.989+01:00",
                        "updated_at": "2024-12-07T14:57:12.989+01:00"
                      },
                      {
                        "id": "f28734c1-0052-554d-a50e-b2356d8c66e4",
                        "migration_identifier": null,
                        "full_width": false,
                        "localizations": {
                          "fr": {
                            "id": "e60b21c3-5968-54b2-93da-4a6a33fc85cc",
                            "migration_identifier": null,
                            "title": "Test 3",
                            "featured_image": {
                              "blob_id": null,
                              "alt": null,
                              "credit": null,
                              "url": null
                            },
                            "meta_description": null,
                            "pinned": null,
                            "published": false,
                            "published_at": "2010-11-28T01:00:00.000+01:00",
                            "slug": "test-3",
                            "subtitle": null,
                            "summary": null,
                            "text": null,
                            "created_at": "2024-12-07T14:57:12.969+01:00",
                            "updated_at": "2024-12-07T14:57:12.969+01:00"
                          }
                        },
                        "created_at": "2024-12-07T14:57:12.989+01:00",
                        "updated_at": "2024-12-07T14:57:12.989+01:00"
                      }
                    ]
                  }
                },
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/communication_website_post"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Please make sure you provide a valid API key.",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized. Please make sure you provide a valid API key.": {
                    "value": {
                      "message": "You are not authorized to access this resource."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Website not found",
            "content": {
              "application/json": {
                "examples": {
                  "Website not found": {
                    "value": {
                      "message": "The resource you were looking for doesn't exist."
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Creates a post",
        "tags": [
          "Communication::Website::Post"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "name": "website_id",
            "in": "path",
            "description": "Website identifier",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Successful creation",
            "content": {
              "application/json": {
                "examples": {
                  "Successful creation": {
                    "value": {
                      "id": "63739aa2-9a6a-4065-9033-515f26065c79",
                      "migration_identifier": "post-from-api-1",
                      "full_width": false,
                      "localizations": {
                        "fr": {
                          "id": "32ab3468-91d8-4d61-b8ba-da70473f9409",
                          "migration_identifier": "post-from-api-1-fr",
                          "title": "Ma nouvelle actualité",
                          "featured_image": {
                            "blob_id": "30510b55-312b-471d-bc58-02e4784c6d76",
                            "alt": "La lumière brille sur les parois du canyon",
                            "credit": "<p>Photo de <a href=\"https://unsplash.com/fr/@johnnzhou\">John Zhou</a> sur <a href=\"https://unsplash.com/fr/photos/la-lumiere-brille-sur-les-parois-du-canyon-AM-G-Yp5hIk\">Unsplash</a></p>",
                            "url": "http://my-university.osuny.test/rails/active_storage/disk/eyJfcmFpbHMiOnsiZGF0YSI6eyJrZXkiOiJtZXZxdDltcnhsZHZzM3ZxNWRjNW56dmZ4enByIiwiZGlzcG9zaXRpb24iOiJpbmxpbmU7IGZpbGVuYW1lPVwicGhvdG8tMTcwMzkyMzYzMzYxNi0yNTRlNzhmNmU5ZGZcIjsgZmlsZW5hbWUqPVVURi04JydwaG90by0xNzAzOTIzNjMzNjE2LTI1NGU3OGY2ZTlkZiIsImNvbnRlbnRfdHlwZSI6ImltYWdlL2pwZWciLCJzZXJ2aWNlX25hbWUiOiJ0ZXN0In0sImV4cCI6IjIwMjQtMTItMDdUMTQ6NTc6MTMuNjkyWiIsInB1ciI6ImJsb2Jfa2V5In19--025e788d97587d27a4847f619f709e18822d5ad2/photo-1703923633616-254e78f6e9df"
                          },
                          "meta_description": "Une nouvelle actualité depuis l'API",
                          "pinned": false,
                          "published": true,
                          "published_at": "2024-11-29T17:49:00.000+01:00",
                          "slug": "ma-nouvelle-actualite",
                          "subtitle": "Une nouvelle actualité",
                          "summary": "<p>Ceci est une nouvelle actualité créée depuis l'API.</p>",
                          "text": null,
                          "created_at": "2024-12-07T14:57:13.554+01:00",
                          "updated_at": "2024-12-07T14:57:13.570+01:00"
                        }
                      },
                      "created_at": "2024-12-07T14:57:13.546+01:00",
                      "updated_at": "2024-12-07T14:57:13.686+01:00"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing migration identifier.",
            "content": {
              "application/json": {
                "examples": {
                  "Missing migration identifier.": {
                    "value": {
                      "error": "Missing migration identifier."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Please make sure you provide a valid API key.",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized. Please make sure you provide a valid API key.": {
                    "value": {
                      "message": "You are not authorized to access this resource."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Website not found",
            "content": {
              "application/json": {
                "examples": {
                  "Website not found": {
                    "value": {
                      "message": "The resource you were looking for doesn't exist."
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "Invalid parameters",
            "content": {
              "application/json": {
                "examples": {
                  "Invalid parameters": {
                    "value": {
                      "errors": {
                        "localizations.slug": [
                          "can't be blank",
                          "ne peut contenir que des lettres minuscules, des chiffres et des traits d'union."
                        ],
                        "localizations.title": [
                          "can't be blank"
                        ],
                        "localizations": [
                          "is invalid"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "post": {
                    "$ref": "#/components/schemas/communication_website_post"
                  }
                },
                "required": [
                  "post"
                ]
              }
            }
          }
        }
      }
    },
    "/communication/websites/{website_id}/posts/{id}": {
      "get": {
        "summary": "Shows a post",
        "tags": [
          "Communication::Website::Post"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "name": "website_id",
            "in": "path",
            "description": "Website identifier",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "path",
            "description": "Post identifier",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "examples": {
                  "Successful operation": {
                    "value": {
                      "id": "03f9a88a-084d-535b-baf7-9008b43969c2",
                      "migration_identifier": "test-post-fixture-1",
                      "full_width": false,
                      "localizations": {
                        "fr": {
                          "id": "16a1d9cf-f9eb-5ded-914d-dd421b5d395b",
                          "migration_identifier": "test-post-fixture-1-fr",
                          "title": "Test",
                          "featured_image": {
                            "blob_id": null,
                            "alt": null,
                            "credit": null,
                            "url": null
                          },
                          "meta_description": null,
                          "pinned": null,
                          "published": true,
                          "published_at": "2010-11-28T01:00:00.000+01:00",
                          "slug": "test",
                          "subtitle": null,
                          "summary": null,
                          "text": null,
                          "created_at": "2024-12-07T14:57:12.969+01:00",
                          "updated_at": "2024-12-07T14:57:12.969+01:00"
                        }
                      },
                      "created_at": "2024-12-07T14:57:12.989+01:00",
                      "updated_at": "2024-12-07T14:57:12.989+01:00"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Please make sure you provide a valid API key.",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized. Please make sure you provide a valid API key.": {
                    "value": {
                      "message": "You are not authorized to access this resource."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Post not found",
            "content": {
              "application/json": {
                "examples": {
                  "Website not found": {
                    "value": {
                      "message": "The resource you were looking for doesn't exist."
                    }
                  },
                  "Post not found": {
                    "value": {
                      "message": "The resource you were looking for doesn't exist."
                    }
                  }
                }
              }
            }
          }
        }
      },
      "patch": {
        "summary": "Updates a post",
        "tags": [
          "Communication::Website::Post"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "name": "website_id",
            "in": "path",
            "description": "Website identifier",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "path",
            "description": "Post identifier",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful update",
            "content": {
              "application/json": {
                "examples": {
                  "Successful update": {
                    "value": {
                      "id": "03f9a88a-084d-535b-baf7-9008b43969c2",
                      "migration_identifier": "test-post-fixture-1",
                      "full_width": false,
                      "localizations": {
                        "fr": {
                          "id": "16a1d9cf-f9eb-5ded-914d-dd421b5d395b",
                          "migration_identifier": "test-post-fixture-1-fr",
                          "title": "Mon nouveau titre",
                          "featured_image": {
                            "blob_id": null,
                            "alt": null,
                            "credit": null,
                            "url": null
                          },
                          "meta_description": null,
                          "pinned": null,
                          "published": true,
                          "published_at": "2010-11-28T01:00:00.000+01:00",
                          "slug": "test",
                          "subtitle": null,
                          "summary": null,
                          "text": null,
                          "created_at": "2024-12-07T14:57:12.969+01:00",
                          "updated_at": "2024-12-07T14:57:13.828+01:00"
                        }
                      },
                      "created_at": "2024-12-07T14:57:12.989+01:00",
                      "updated_at": "2024-12-07T14:57:13.832+01:00"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Missing migration identifier.",
            "content": {
              "application/json": {
                "examples": {
                  "Missing migration identifier.": {
                    "value": {
                      "error": "Missing migration identifier."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Please make sure you provide a valid API key.",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized. Please make sure you provide a valid API key.": {
                    "value": {
                      "message": "You are not authorized to access this resource."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Post not found",
            "content": {
              "application/json": {
                "examples": {
                  "Website not found": {
                    "value": {
                      "message": "The resource you were looking for doesn't exist."
                    }
                  },
                  "Post not found": {
                    "value": {
                      "message": "The resource you were looking for doesn't exist."
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "Invalid parameters",
            "content": {
              "application/json": {
                "examples": {
                  "Invalid parameters": {
                    "value": {
                      "errors": {
                        "localizations.title": [
                          "can't be blank"
                        ],
                        "localizations": [
                          "is invalid"
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "post": {
                    "$ref": "#/components/schemas/communication_website_post"
                  }
                },
                "required": [
                  "post"
                ]
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Deletes a post",
        "tags": [
          "Communication::Website::Post"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "name": "website_id",
            "in": "path",
            "description": "Website identifier",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "id",
            "in": "path",
            "description": "Post identifier",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Successful deletion"
          },
          "401": {
            "description": "Unauthorized. Please make sure you provide a valid API key.",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized. Please make sure you provide a valid API key.": {
                    "value": {
                      "message": "You are not authorized to access this resource."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Post not found",
            "content": {
              "application/json": {
                "examples": {
                  "Website not found": {
                    "value": {
                      "message": "The resource you were looking for doesn't exist."
                    }
                  },
                  "Post not found": {
                    "value": {
                      "message": "The resource you were looking for doesn't exist."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/communication/websites": {
      "get": {
        "summary": "Lists the websites",
        "tags": [
          "Communication::Website"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "examples": {
                  "Successful operation": {
                    "value": [
                      {
                        "id": "39d8ed64-c1b7-52d3-9095-025a5742a04f",
                        "url": null,
                        "deuxfleurs": {
                          "hosting": false,
                          "identifier": null
                        },
                        "features": {
                          "agenda": true,
                          "portfolio": false,
                          "posts": true
                        },
                        "git": {
                          "branch": "main",
                          "endpoint": null,
                          "provider": "github",
                          "repository": "noesya/bordeauxmontaigne-test"
                        },
                        "showcase": {
                          "present": true,
                          "highlighted": false,
                          "tags": []
                        },
                        "localizations": {
                          "fr": {
                            "id": "3d91a284-4159-504e-81c5-6b9b32a08dd7",
                            "name": "Site with github french",
                            "published": true,
                            "published_at": "2024-11-29T16:07:24.232+01:00",
                            "social_email": null,
                            "social_facebook": null,
                            "social_github": null,
                            "social_instagram": null,
                            "social_linkedin": null,
                            "social_mastodon": null,
                            "social_peertube": null,
                            "social_tiktok": null,
                            "social_vimeo": null,
                            "social_x": null,
                            "social_youtube": null,
                            "created_at": "2024-12-07T14:57:12.935+01:00",
                            "updated_at": "2024-12-07T14:57:12.935+01:00"
                          }
                        },
                        "created_at": "2024-12-07T14:57:12.991+01:00",
                        "updated_at": "2024-12-07T14:57:12.991+01:00"
                      },
                      {
                        "id": "a3f63673-fb05-5751-8634-a2a8bccc1f3d",
                        "url": null,
                        "deuxfleurs": {
                          "hosting": false,
                          "identifier": null
                        },
                        "features": {
                          "agenda": false,
                          "portfolio": false,
                          "posts": true
                        },
                        "git": {
                          "branch": "main",
                          "endpoint": null,
                          "provider": "gitlab",
                          "repository": "33848340"
                        },
                        "showcase": {
                          "present": true,
                          "highlighted": false,
                          "tags": []
                        },
                        "localizations": {
                          "fr": {
                            "id": "b854339d-f776-59c7-af65-e12ee2951daa",
                            "name": "Site with gitlab french",
                            "published": true,
                            "published_at": "2024-11-29T16:07:24.232+01:00",
                            "social_email": null,
                            "social_facebook": null,
                            "social_github": null,
                            "social_instagram": null,
                            "social_linkedin": null,
                            "social_mastodon": null,
                            "social_peertube": null,
                            "social_tiktok": null,
                            "social_vimeo": null,
                            "social_x": null,
                            "social_youtube": null,
                            "created_at": "2024-12-07T14:57:12.935+01:00",
                            "updated_at": "2024-12-07T14:57:12.935+01:00"
                          },
                          "en": {
                            "id": "f55e6093-cf39-525e-b83c-331d90fad1c6",
                            "name": "Site with gitlab english",
                            "published": true,
                            "published_at": "2024-11-29T16:07:24.232+01:00",
                            "social_email": null,
                            "social_facebook": null,
                            "social_github": null,
                            "social_instagram": null,
                            "social_linkedin": null,
                            "social_mastodon": null,
                            "social_peertube": null,
                            "social_tiktok": null,
                            "social_vimeo": null,
                            "social_x": null,
                            "social_youtube": null,
                            "created_at": "2024-12-07T14:57:12.935+01:00",
                            "updated_at": "2024-12-07T14:57:12.935+01:00"
                          }
                        },
                        "created_at": "2024-12-07T14:57:12.991+01:00",
                        "updated_at": "2024-12-07T14:57:12.991+01:00"
                      }
                    ]
                  }
                },
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/communication_website"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Please make sure you provide a valid API key.",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized. Please make sure you provide a valid API key.": {
                    "value": {
                      "message": "You are not authorized to access this resource."
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/communication/websites/{id}": {
      "get": {
        "summary": "Shows a website",
        "tags": [
          "Communication::Website"
        ],
        "security": [
          {
            "api_key": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Website identifier",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "examples": {
                  "Successful operation": {
                    "value": {
                      "id": "39d8ed64-c1b7-52d3-9095-025a5742a04f",
                      "url": null,
                      "deuxfleurs": {
                        "hosting": false,
                        "identifier": null
                      },
                      "features": {
                        "agenda": true,
                        "portfolio": false,
                        "posts": true
                      },
                      "git": {
                        "branch": "main",
                        "endpoint": null,
                        "provider": "github",
                        "repository": "noesya/bordeauxmontaigne-test"
                      },
                      "showcase": {
                        "present": true,
                        "highlighted": false,
                        "tags": []
                      },
                      "localizations": {
                        "fr": {
                          "id": "3d91a284-4159-504e-81c5-6b9b32a08dd7",
                          "name": "Site with github french",
                          "published": true,
                          "published_at": "2024-11-29T16:07:24.232+01:00",
                          "social_email": null,
                          "social_facebook": null,
                          "social_github": null,
                          "social_instagram": null,
                          "social_linkedin": null,
                          "social_mastodon": null,
                          "social_peertube": null,
                          "social_tiktok": null,
                          "social_vimeo": null,
                          "social_x": null,
                          "social_youtube": null,
                          "created_at": "2024-12-07T14:57:12.935+01:00",
                          "updated_at": "2024-12-07T14:57:12.935+01:00"
                        }
                      },
                      "created_at": "2024-12-07T14:57:12.991+01:00",
                      "updated_at": "2024-12-07T14:57:12.991+01:00"
                    }
                  }
                },
                "schema": {
                  "$ref": "#/components/schemas/communication_website"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized. Please make sure you provide a valid API key.",
            "content": {
              "application/json": {
                "examples": {
                  "Unauthorized. Please make sure you provide a valid API key.": {
                    "value": {
                      "message": "You are not authorized to access this resource."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Website not found",
            "content": {
              "application/json": {
                "examples": {
                  "Website not found": {
                    "value": {
                      "message": "The resource you were looking for doesn't exist."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}